# Generated by Django 4.1.4 on 2022-12-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmptagmenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('ancestor', models.IntegerField()),
                ('descendant', models.IntegerField()),
                ('depth', models.IntegerField()),
            ],
        ),
    ]
